### PR TITLE
Feat add script output to run

### PR DESCRIPTION
**Pull request by PatrickAlphaC**
… no arguments specified for `brownie run`

### What I did

`brownie run` will now output the scripts directory and 1 level deep of subdirectory. If you use the [yearn brownie mix](https://github.com/iearn-finance/brownie-strategy-mix) and run `brownie run` without any parameters, you'll get this output:

```
Brownie v1.12.2 - Python development framework for Ethereum

YearnStrategyProject is the active project.
scripts/
    deploy.py
    random_script/
        test.py

Usage: brownie run <filename> [<function>] [options]
```

Related issue: #

https://github.com/eth-brownie/brownie/issues

### How I did it

Added a check in the `run.py` main function looking for argument length, it's it's less than 3, print out the scripts. 

### How to verify it

`brownie run` will output all the scripts in the `scripts` directory. 

### Checklist

- [X] I have confirmed that my PR passes all linting checks
- [X] I have included test cases
- [Not needed] I have updated the documentation
- [X] I have added an entry to the changelog

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Open to learning how to fix the lint issues and improvements to the PRs.

Talk soon!

**Comment by iamdefinitelyahuman** [comment]
The tests that were failing should now be fixed if you rebase :pray:

**Comment by PatrickAlphaC** [comment]
Updated with `path` instead of `os`. The output is a little different, but functionally is the same.

**Review by iamdefinitelyahuman — COMMENTED** [review]
Overall looks good!  One minor tweak and then ready to merge :rocket:

**Comment by PatrickAlphaC** [comment]
> Overall looks good! One minor tweak and then ready to merge 🚀

Thanks for the meticulous attention to detail, happy to keep the code style uniform.

**Comment by NikitaPirate** [comment]
Sorry but i do it too. And I was assigned. And I think I solved the problem more completely. But I still work on tests... https://github.com/eth-brownie/brownie/pull/903

**Comment by PatrickAlphaC** [comment]
Ah I like yours better too! I'll wait on yours to pass tests and let you take the issue here. I'll wait to close my PR.

**Comment by PatrickAlphaC** [comment]
closing. Someone else was getting this.

**Pull request closed without merging**
