### PR TITLE
soft and hard requirements

### PR DESCRIPTION
**Pull request by WyseNynja**
### What I did

Related issue: #991

### How I did it

Added an environment variable to allow the use of soft instead of hard pins.

### How to verify it

`pip install .` and see that everything has hard pins

`BROWNIE_LIB=1 pip install .` and see that everything has soft pins.

### Checklist

- [ ] I have confirmed that my PR passes all linting checks
- [ ] I have included test cases
- [x] I have updated the documentation
- [x] I have added an entry to the changelog

### CODE REVIEW

**Comment by WyseNynja** [comment]
The only issue I'm seeing now is that `colorama>=0.4.1;platform_system=='Windows'` doesn't show up in requirements.txt as expected

**Comment by WyseNynja** [comment]
We should upgrade things in a separate PR:
```
pip list --outdated
Package        Version Latest Type
-------------- ------- ------ -----
bitarray       1.2.2   1.7.1  sdist
eth-account    0.5.2   0.5.4  wheel
eth-hash       0.2.0   0.3.1  wheel
eth-utils      1.9.5   1.10.0 wheel
hypothesis     5.41.3  6.8.1  wheel
idna           2.10    3.1    wheel
inflection     0.5.0   0.5.1  wheel
mythx-models   1.9.1   2.1.0  wheel
prompt-toolkit 3.0.8   3.0.17 wheel
Pygments       2.6.1   2.8.1  wheel
PyJWT          1.7.1   2.0.1  wheel
pytest         6.0.1   6.2.2  wheel
pytest-xdist   1.34.0  2.2.1  wheel
pythx          1.6.1   1.7.1  wheel
rlp            1.2.0   2.0.1  wheel
setuptools     53.0.0  54.1.2 wheel
tqdm           4.53.0  4.59.0 wheel
web3           5.11.1  5.17.0 wheel
```

**Comment by WyseNynja** [comment]
I think this way of handling windows will work. If colorama does more platform specific things, they might not have full pins, but I think that will be okay.

**Comment by iamdefinitelyahuman** [comment]
Agreed that some dependencies are overdue for a bump.  In particular `web3`, `pytest` and `hypothesis` are all out of date, but things break if bumped.

**Review by iamdefinitelyahuman — APPROVED** [review]
Thank you very much for this :pray:

**Pull request merged**
