### PR TITLE
feat: allow cache disabling with forks

### PR DESCRIPTION
**Pull request by 7xAquarius**
### Motivation
I keep getting `RPCProcessError: Unable to launch local RPC client.` when I try to fork Avalanche mainnet and testnet.
It's usually one of both working, while the other results in an error.

However, forking with `--fork.disableCache` on ganache fixes the issue.

### What I did
Added support for cache disabling with forks

### How I did it
Added support for the already existing `--fork.disableCache` option from ganache

### How to verify it
Add any forked network with `--disable_cache=true` and launch it
or in config file
```
networks:
    avax-fork:
        cmd_settings:
            disable_cache: true
```

### Sidenote

ganache also has the `--fork.deleteCache` option, both works for my issue but idk

### Checklist

- [x] I have confirmed that my PR passes all linting checks
- [x] I have included test cases
- [x] I have updated the documentation
- [x] I have added an entry to the changelog

### CODE REVIEW

**Comment by WyseNynja** [comment]
I don't think we want to disable cache for all development networks. It can be very helpful on other chains. Can we change this to just disable for avalanche since it doesn't work there?

**Comment by 7xAquarius** [comment]
I agree.
This PR only allows the option to be used, it's not enabled by default on any network.

Maybe I should remove it from `test_validate_cmd_settings()`, is that what you meant ?

**Comment by WyseNynja** [comment]
From your example comment, I just thought you'd set the default to "true". The default should be "false"

**Comment by 7xAquarius** [comment]
I've replaced `development` with `avax-fork` in my config file example, might be easier to understand you're right.

I don't think the default value needs to be set to `false` somewhere. Similar to the `fork` option, you set it when you need it.
In fact, it only works when `fork` option is set

**Review by iamdefinitelyahuman — APPROVED** [review]

**Pull request merged**
