### PR TITLE
Bumps Web3.py to >=5.11.1,<=5.14.0

### PR DESCRIPTION
**Pull request by omarish**
### What I did

* Updated web3.py to `>=5.11.1,<=5.14.0`
* This is a draft PR and haven't added any new tests yet.

Related issue:

* https://github.com/eth-brownie/brownie/issues/943

### Checklist

- [ ] I have confirmed that my PR passes all linting checks
- [ ] I have included test cases
- [ ] I have updated the documentation
- [ ] I have added an entry to the changelog

### CODE REVIEW

**Comment by iamdefinitelyahuman** [comment]
I generally prefer to strictly pin dependencies.  In the past, `web3` has made breaking changes in patch versions.

That said, happy to move to a newer version.  Just haven't had the bandwidth to deal with changes in `5.12.0` that were causing tests to fail.

**Comment by omarish** [comment]
Understood, that makes sense and I think strict pinning is probably the safe strategy, especially if `web3` has previously made breaking changes in patch versions. 

Looks like some of the test failures you mentioned are showing up here already. Will try and work through these when I can.

**Comment by iamdefinitelyahuman** [comment]
This was handled in #1064

**Comment by omarish** [comment]
Amazing. Nicely done, @skellet0r!

**Pull request closed without merging**
