### PR TITLE
feat(network-config): Update optimism-test

### PR DESCRIPTION
**Pull request by qbzzt**
Optimism is [transitioning the testnet from Kovan to Goerli](https://dev.optimism.io/kovan-to-goerli).

### What I did

Related issue: N/A

### How I did it

Changed configuration values

### How to verify it

Run whatever you used to run on Optimism Kovan, see it runs on the Optimism Goerli network

### Checklist

None, really minor change.

### CODE REVIEW

**Comment by stas** [comment]
Hey @qbzzt any reasons why this was closed?

Optimism Kovan is no longer available.

**Comment by qbzzt** [comment]
I just deleted old repositories. Brownie doesn't seem to be under development anymore. Is it? If so, I'll reopen.

**Comment by stas** [comment]
Hmm looks like it's still updated to me lol, cc @iamdefinitelyahuman

**Comment by qbzzt** [comment]
Reopened. I hope it can be merged soon.

**Review by stas — APPROVED** [review]
Thank you!

**Comment by iamdefinitelyahuman** [comment]
One year later...

**Review by iamdefinitelyahuman — APPROVED** [review]

**Comment by iamdefinitelyahuman** [comment]
Ahh, head is deleted..  I'll add in a fresh PR.  Thanks for this and sorry for the huge wait,

**Pull request closed without merging**
